import { IPaymentMethod } from './PaymentMethod';
import { IProperties } from './Properties';

export interface IOrderInPayment extends IDefaultObj {
  orderId: string;
  purpose?: string;
  gatewayCode: string;
  paymentMethod: IPaymentMethod;
  organizationId?: string;
  organizationName?: string;
  customerId: string;
  customerName?: string;
  incomingDate?: Date;
  billingAddress?: string;
  paymentStatus: string;
  authorizedDate?: Date;
  capturedDate?: Date;
  voidedDate?: Date;
  processPaymentResult?: string;
  price: number;
  priceWithTax: number;
  total: number;
  totalWithTax: number;
  discountAmount: number;
  discountAmountWithTax: number;
  objectType: string;
  feeDetails: Array<any>;
  vendorId: string;
  taxType?: string;
  taxTotal: number;
  taxPercentRate: number;
  taxDetails: Array<any>;
  discounts: Array<any>;
  transactions: Array<any>;
  refunds: Array<any>;
  captures: Array<any>;
  operationType: string;
  parentOperationId?: string;
  number: string;
  isApproved: boolean;
  status: string;
  comment?: string;
  currency: string;
  sum: number;
  outerId?: string;
  childrenOperations: Array<any>;
  cancelledState: string;
  isCancelled: boolean;
  cancelledDate?: Date;
  cancelReason?: string;
  dynamicProperties: Array<IProperties>;
  operationsLog?: string;
}
