import { IProductImage } from './ProductImage';
import { IProperties } from './Properties';
import { IProductAsset } from './ProductAsset';
import { ISEOInfo } from './SEOInfo';
import { IProductReview } from './ProductReview';
import { IProductAssociation } from './ProductAssociation';
import { IOutlineItem } from './OutlineItem';
export interface IProductItem extends IDefaultObj {
  productType: string;
  code: string;
  manufacturerPartNumber: string;
  gtin?: string;
  name: string;
  catalogId: string;
  categoryId: string;
  outline: string;
  path: string;
  titularItemId?: string;
  mainProductId?: string;
  isActive: boolean;
  isBuyable: boolean;
  trackInventory: boolean;
  indexingDate?: string;
  maxQuantity: number;
  minQuantity: number;
  startDate: Date;
  endDate: string;
  packageType?: string;
  weightUnit?: string;
  weight?: number;
  measureUnit?: string;
  height?: string;
  length?: string;
  width?: string;
  enableReview?: string;
  maxNumberOfDownload?: number;
  downloadExpiration?: string;
  downloadType?: string;
  hasUserAgreement?: string;
  shippingType?: string;
  taxType?: string;
  vendor: string;
  priority: number;
  outerId?: string;
  excludedProperties?: string;
  propertyValues?: string;
  imgSrc: string;
  variations?: Array<IProductItem>;
  seoObjectType: string;
  isInherited: boolean;
  parentCategoryIsActive: boolean;
  properties?: Array<IProperties>;
  images?: Array<IProductImage>;
  assets?: Array<IProductAsset>;
  links?: Array<any>;
  seoInfos?: Array<ISEOInfo>;
  reviews?: Array<IProductReview>;
  associations?: Array<IProductAssociation>;
  referencedAssociations?: Array<any>;
  outlines?: Array<{ items?: Array<IOutlineItem> }>;
}
export interface IProductsList extends Array<IProductItem> {}
